import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider, SignIn, SignedIn, SignedOut } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "RentAcar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          {/* if the user is signed in, show the children, else show the sign in page */}
          <SignedIn>
            {children}
          </SignedIn>

          <SignedOut>
            <SignIn />
          </SignedOut>

        </body>
      </html>
    </ClerkProvider>
  );
}
